### ISSUE TITLE
Change versioning scheme

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter.ErrorCodes#22]
Minor version should reflect bugfixes or non-breaking code changes, not commit count.
Patch version should reflect number of error messages (or commit count).

Probabably requires generating `.nuspec` file as part of code generation, but gets rid of calculating version numbers in build scripts.

**Comment by chrhol** [comment]
Thanks for the feedback. I will do it as soon as I am finished with my current task.

**Comment by chrhol** [comment]
Implemented. Major and minor version has to be bumped manually. The patchnumber is the number of errorcodes, which means that since we always add, never remove codes, each new code will have a higher patchversion. And bugfixes or other changes will take precedence.

I did not generate a nuspec though, I wanted to have the built assemblies be stamped with the same version so instead the count is outputted and used as part of the version.

The batch script have been simplifed alot.
